server:
  port: 1940

spring:
  application:
    name: cloud-demo

  # liquibase
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml
    enabled: true

 # datasource
  datasource:
    username: sa
    password: password
    url: jdbc:h2:mem:testdb

  #jpa
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  #h2
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true